import { NextResponse } from 'next/server';
import prisma from '@/lib/db';
import { auth } from '@/lib/auth';
import { vpnConfigSchema } from '@/lib/validation';
import { v4 as uuidv4 } from 'uuid';

// Generate a WireGuard-style config (simulated)
function generateWireGuardConfig(serverLocation: string) {
    const privateKey = Buffer.from(uuidv4() + uuidv4()).toString('base64').slice(0, 44);
    const publicKey = Buffer.from(uuidv4() + uuidv4()).toString('base64').slice(0, 44);

    return `[Interface]
PrivateKey = ${privateKey}
Address = 10.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255) + 1}/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = ${publicKey}
Endpoint = ${serverLocation}.vpn.notrespond.com:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25`;
}

// Generate an OpenVPN config (simulated)
function generateOpenVPNConfig(serverLocation: string) {
    return `client
dev tun
proto udp
remote ${serverLocation}.vpn.notrespond.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA256
cipher AES-256-GCM
verb 3
<ca>
-----BEGIN CERTIFICATE-----
# Certificate would be generated by the actual VPN server
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
# Client certificate
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
# Client private key
-----END PRIVATE KEY-----
</key>`;
}

export async function POST(request: Request) {
    try {
        const session = await auth();
        if (!session?.user?.id) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const body = await request.json();
        const parsed = vpnConfigSchema.safeParse(body);

        if (!parsed.success) {
            return NextResponse.json(
                { error: 'Invalid input', details: parsed.error.flatten().fieldErrors },
                { status: 400 }
            );
        }

        const { protocol, serverLocation } = parsed.data;

        // Generate config based on protocol
        let configData: string;
        if (protocol === 'wireguard') {
            configData = generateWireGuardConfig(serverLocation);
        } else if (protocol === 'openvpn') {
            configData = generateOpenVPNConfig(serverLocation);
        } else {
            configData = `# IKEv2 configuration for ${serverLocation}\n# Server: ${serverLocation}.vpn.notrespond.com`;
        }

        // Store config in database
        const vpnConfig = await prisma.vpnConfig.create({
            data: {
                userId: session.user.id,
                orderId: 'demo-order', // In production, link to real order
                protocol,
                serverLocation,
                configData,
                expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days
            },
        });

        return NextResponse.json({
            config: vpnConfig,
            downloadFilename: `${protocol}-${serverLocation}.${protocol === 'wireguard' ? 'conf' : 'ovpn'}`,
        });
    } catch (error) {
        console.error('VPN config generation error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
